version: '3.8'
services:
  nuxt:
    build: ./nuxt
    ports:
      - 9001:3000
    volumes:
      - ./nuxt/src:/nuxt
    working_dir: /nuxt
    command: npm run dev

  go:
    build: ./go
    command: go run main.go
    volumes:
      - ./go/src:/go
    working_dir: /go
    ports:
      - "8080:8080"