version: '3.8'
services:
  nuxt:
    build: ./nuxt
    ports:
      - 9001:3000
    volumes:
      - ./nuxt/src:/nuxt
    working_dir: /nuxt
    command: npm run dev

  go:
    build: ./go
    command: go run main.go
    volumes:
      - ./go/src:/go
    working_dir: /go
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  db:
    image: postgres:14.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      TZ: 'Asia/Tokyo'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5430:5432
      
volumes:
  pgdata: